id: PA1D655A5
initial_creation_type: ocr
source_metadata:
  volumes:
    36c1ee5ee1a74ed3a12dae96914ee8c3:
      base_file: v014.txt
      image_group_id: I1PD95859
      title: དཔལ་ནག་པོ་ཆེན་པོ་ཡུམ་ཅན་གྱི་སྒྲུབ་ཐབས།
      total_pages: 1856
      volume_number: 14
